// <auto-generated />
namespace Biblio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClanoviBrKnjiga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClanoviBrKnjiga));
        
        string IMigrationMetadata.Id
        {
            get { return "202009031725284_ClanoviBrKnjiga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
